[functions.website-analyzer-v3]
verify_jwt = false


[functions.project-ingestion]
verify_jwt = false

[functions.gecko-token-discovery]
verify_jwt = false

[functions.website-discovery]
verify_jwt = false

[functions.x-analyzer]
verify_jwt = false

[functions.ultra-tracker]
verify_jwt = false

[functions.whitepaper-analyzer]
verify_jwt = false

