[functions.website-analyzer-v3]
verify_jwt = false


[functions.website-analyzer]
verify_jwt = false

[functions.project-ingestion]
verify_jwt = false

[functions.gecko-token-discovery]
verify_jwt = false

[functions.website-discovery]
verify_jwt = false

[functions.x-analyzer]
verify_jwt = false

[functions.ultra-tracker]
verify_jwt = false

[functions.whitepaper-analyzer]
verify_jwt = false


[functions.whitepaper-analyzer-v2]
enabled = true
verify_jwt = true
import_map = "./functions/whitepaper-analyzer-v2/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whitepaper-analyzer-v2/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whitepaper-analyzer-v2/*.html" ]

[functions.whitepaper-fetcher]
enabled = true
verify_jwt = true
import_map = "./functions/whitepaper-fetcher/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whitepaper-fetcher/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whitepaper-fetcher/*.html" ]
