// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/benchmarks" | "/admin/dashboard" | "/admin/domains" | "/admin/prompts" | "/project/[symbol]"
type AppRouteHandlerRoutes = "/api/add-token" | "/api/admin/ai-prompts" | "/api/admin/auth" | "/api/admin/benchmarks" | "/api/admin/benchmarks/[id]" | "/api/admin/delete-project" | "/api/admin/excluded-domains" | "/api/admin/imposter" | "/api/capture-screenshot" | "/api/crypto-projects-rated" | "/api/signal-feedback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/benchmarks": {}
  "/admin/dashboard": {}
  "/admin/domains": {}
  "/admin/prompts": {}
  "/api/add-token": {}
  "/api/admin/ai-prompts": {}
  "/api/admin/auth": {}
  "/api/admin/benchmarks": {}
  "/api/admin/benchmarks/[id]": { "id": string; }
  "/api/admin/delete-project": {}
  "/api/admin/excluded-domains": {}
  "/api/admin/imposter": {}
  "/api/capture-screenshot": {}
  "/api/crypto-projects-rated": {}
  "/api/signal-feedback": {}
  "/project/[symbol]": { "symbol": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
