// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/benchmarks/page.tsx
{
  const handler = {} as typeof import("../../app/admin/benchmarks/page.js")
  handler satisfies AppPageConfig<"/admin/benchmarks">
}

// Validate ../../app/admin/dashboard/page.tsx
{
  const handler = {} as typeof import("../../app/admin/dashboard/page.js")
  handler satisfies AppPageConfig<"/admin/dashboard">
}

// Validate ../../app/admin/domains/page.tsx
{
  const handler = {} as typeof import("../../app/admin/domains/page.js")
  handler satisfies AppPageConfig<"/admin/domains">
}

// Validate ../../app/admin/page.tsx
{
  const handler = {} as typeof import("../../app/admin/page.js")
  handler satisfies AppPageConfig<"/admin">
}

// Validate ../../app/admin/prompts/page.tsx
{
  const handler = {} as typeof import("../../app/admin/prompts/page.js")
  handler satisfies AppPageConfig<"/admin/prompts">
}

// Validate ../../app/page.tsx
{
  const handler = {} as typeof import("../../app/page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ../../app/project/[symbol]/page.tsx
{
  const handler = {} as typeof import("../../app/project/[symbol]/page.js")
  handler satisfies AppPageConfig<"/project/[symbol]">
}

// Validate ../../app/api/add-token/route.ts
{
  const handler = {} as typeof import("../../app/api/add-token/route.js")
  handler satisfies RouteHandlerConfig<"/api/add-token">
}

// Validate ../../app/api/admin/ai-prompts/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/ai-prompts/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/ai-prompts">
}

// Validate ../../app/api/admin/auth/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/auth/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/auth">
}

// Validate ../../app/api/admin/benchmarks/[id]/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/benchmarks/[id]/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/benchmarks/[id]">
}

// Validate ../../app/api/admin/benchmarks/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/benchmarks/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/benchmarks">
}

// Validate ../../app/api/admin/delete-project/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/delete-project/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/delete-project">
}

// Validate ../../app/api/admin/excluded-domains/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/excluded-domains/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/excluded-domains">
}

// Validate ../../app/api/admin/imposter/route.ts
{
  const handler = {} as typeof import("../../app/api/admin/imposter/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/imposter">
}

// Validate ../../app/api/capture-screenshot/route.ts
{
  const handler = {} as typeof import("../../app/api/capture-screenshot/route.js")
  handler satisfies RouteHandlerConfig<"/api/capture-screenshot">
}

// Validate ../../app/api/crypto-projects-rated/route.ts
{
  const handler = {} as typeof import("../../app/api/crypto-projects-rated/route.js")
  handler satisfies RouteHandlerConfig<"/api/crypto-projects-rated">
}

// Validate ../../app/api/signal-feedback/route.ts
{
  const handler = {} as typeof import("../../app/api/signal-feedback/route.js")
  handler satisfies RouteHandlerConfig<"/api/signal-feedback">
}





// Validate ../../app/admin/layout.tsx
{
  const handler = {} as typeof import("../../app/admin/layout.js")
  handler satisfies LayoutConfig<"/admin">
}

// Validate ../../app/layout.tsx
{
  const handler = {} as typeof import("../../app/layout.js")
  handler satisfies LayoutConfig<"/">
}
